version: 2
updates:
  - package-ecosystem: npm
    directory:
      - /
      - /build/migration
    schedule:
      interval: monthly
    target-branch: develop
    ignore:
      - dependency-name: "riot"
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: monthly
    target-branch: develop
